name: Zip & Upload Artifact

description: Zips Artifact and then Uploads it to GitHub

inputs:
  # These are the same inputs as the Upload Artifact action.
  # https://github.com/actions/upload-artifact
  name:
    description: The Artifact name
    default: artifact
  path:
    description: A file, directory, or wildcard pattern that describes what to upload
    required: true
  if-no-files-found:
    description: |
      The action to take if no files are found at the path:

      Options:
      - warn: Warning sent, but build does not fail
      - error: Error sent, and build fails
      - info: Nothing sent, and build does not fail
    default: warn
  retention-days:
    description: |
      The number of days to retain the artifact before it expires. Value cannot be over 30 days
    default: '15'

runs:
  using: 'composite'
  steps:
    - name: Perform Validations on inputs
      id: validate_inputs
      shell: python
      run: |
        import os
        echo "Validate Name and Path"
        input_name = os.getenv('INPUT_NAME')
        print(f'Input Name = {input_name}')

        input_path = os.getenv('INPUT_PATH')
        print(f'Input Path = {input_path}')

        is_directory = os.path.isdir(input_path)
        print(f'Is Path Directory? {is_directory}')

        is_file = os.path.isfile(input_path)
        print(f'Is Path File? {is_file}')

        os.environ['PATH_IS_FILE'] = is_file
        os.environ['PATH_IS_DIRECTORY'] = is_directory
      env:
        INPUT_NAME: ${{ inputs.name }}
        INPUT_PATH: ${{ inputs.path }}

    - name: Zip Artifact File
      if: env.PATH_IS_FILE == 'True'
      shell: pwsh
      run: |
        echo "Zipping ${{ inputs.name }}"
        Compress-Archive -Path ./${{ inputs.path }} -DestinationPath "./${{ inputs.path }}.zip"

    - name: Zip Artifact Directory Files
      if: env.PATH_IS_DIRECTORY == 'True'
      shell: pwsh
      run: |
        echo "Zipping ${{ inputs.name }}"
        Compress-Archive -Path ./${{ inputs.path }}/* -DestinationPath "./${{ inputs.path }}/${{ inputs.name }}.zip"

    - name: Upload Artifact Directory Files
      if: env.PATH_IS_DIRECTORY == 'True'
      uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.name}}
        path: ${{ inputs.path }}/${{ inputs.name }}.zip
        if-no-files-found: ${{ inputs.if-no-files-found }}
        retention-days: ${{ inputs.retention-days }}

    - name: Upload Artifact File
      if: env.PATH_IS_FILE == 'True'
      uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.name }}
        path: ${{ inputs.path }}.zip
