name: Zip & Upload Artifact

description: Zips Artifact and then Uploads it to GitHub

inputs:
  # These are the same inputs as the Upload Artifact action.
  # https://github.com/actions/upload-artifact
  name:
    description: The Artifact name
    default: artifact
  path:
    description: A file, directory, or wildcard pattern that describes what to upload
    required: true
  if-no-files-found:
    description: |
      The action to take if no files are found at the path:

      Options:
      - warn: Warning sent, but build does not fail
      - error: Error sent, and build fails
      - info: Nothing sent, and build does not fail
    default: warn
  retention-days:
    description: |
      The number of days to retain the artifact before it expires. Value cannot be over 30 days
    default: '15'

runs:
  using: 'composite'
  steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Install Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'

    - name: Create Artifact Zip
      shell: bash
      run: python3 ./src/zipper.py
      env:
        FILE_NAME: ${{ inputs.name }}
        FILE_PATH: ${{ inputs.path }}
    
    - name: Print size of zip file
      shell: bash
      run: du -sh ${{ inputs.name }}.zip

    - name: Upload Artifact
      uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.name }}
        path: ${{ inputs.name}}.zip
        if-no-files-found: ${{ inputs.if-no-files-found }}
        retention-days: ${{ inputs.retention-days }}
