name: Zip & Upload Artifact

description: Zips Artifact and then Uploads it to GitHub

inputs:
  # These are the same inputs as the Upload Artifact action.
  # https://github.com/actions/upload-artifact
  name:
    description: The Artifact name
    default: artifact
  path:
    description: A file, directory, or wildcard pattern that describes what to upload
    required: true
  if-no-files-found:
    description: |
      The action to take if no files are found at the path:

      Options:
      - warn: Warning sent, but build does not fail
      - error: Error sent, and build fails
      - info: Nothing sent, and build does not fail
    default: warn
  retention-days:
    description: |
      The number of days to retain the artifact before it expires. Value cannot be over 30 days
    default: '15'

runs:
  using: 'composite'
  steps:
    - name: Perform Validations on inputs
      id: validate_inputs
      shell: python
      run: |
        import os
        print('#######################################')
        print('Validate Name and Path Inputs')
        print('#######################################')
        print('')

        input_name = os.getenv('INPUT_NAME')
        print(f'- Input Name = {input_name}')

        input_path = os.getenv('INPUT_PATH')
        print(f'- Input Path = {input_path}')

        is_file = os.path.isfile(input_path)
        print(f'- Is Input Path File? {is_file}')

        def set_env(name, value):
          name_value = f'{name}={value}

          github_output = os.getenv('GITHUB_OUTPUT')
          print(f'- GitHub Output = {github_output}')
          print(f'- Set -> {name_value}')

          with open(github_output, 'a+') as writer:
            writer.write(f'{name_value}{os.linesep}')

        path_type = 'file' if is_file else 'directory'
        set_env('PATH_TYPE', path_type)
      env:
        INPUT_NAME: ${{ inputs.name }}
        INPUT_PATH: ${{ inputs.path }}

    - name: Zip Artifact File
      if: steps.validate_inputs.outputs.PATH_TYPE == 'file'
      shell: pwsh
      run: |
        echo "Zipping Artifact File..."
        Compress-Archive -Path ./${{ inputs.path }} -DestinationPath "./${{ inputs.path }}.zip"
        echo "DONE!"

    - name: Zip Artifact Directory Files
      if: steps.validate_inputs.outputs.PATH_TYPE == 'directory'
      shell: pwsh
      run: |
        echo "Zipping Artifact Directory Files..."
        Compress-Archive -Path ./${{ inputs.path }}/* -DestinationPath "./${{ inputs.path }}/${{ inputs.name }}.zip"
        echo "DONE!"

    - name: Upload Artifact File
      if: steps.validate_inputs.outputs.PATH_TYPE == 'file'
      uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.name }}
        path: ${{ inputs.path }}.zip

    - name: Upload Artifact Directory Files
      if: steps.validate_inputs.outputs.PATH_TYPE == 'directory'
      uses: actions/upload-artifact@v3
      with:
        name: ${{ inputs.name}}
        path: ${{ inputs.path }}/${{ inputs.name }}.zip
        if-no-files-found: ${{ inputs.if-no-files-found }}
        retention-days: ${{ inputs.retention-days }}
