name: Test Zip Upload Artifact

on:
  workflow_dispatch:

jobs:
  test-zip-upload-artifact:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Create Test Files
      shell: python
      run: |
        import os

        def create_file(path_file):
          two_mb = 2 * 1024 * 1024
          print(f"Create file at: {path_file}")
          with open(path_file, "w") as writer:
            writer.write("*" * two_mb)

        dir_results = "test_results"
        os.mkdir(dir_results)

        path_file_0 = "file_0.txt"
        create_file(path_file_0)

        path_file_1 = os.path.join(dir_results, "file_1.txt")
        create_file(path_file_1)

        path_file_2 = os.path.join(dir_results, "file_2.txt")
        create_file(path_file_2)

    - name: Show files in root
      shell: bash
      run: |
        pwd
        ls -la

    - name: Test Directory With Files
      if: always()
      uses: .
      with:
        name: Directory With Text Files
        path: test_results
        retention-days: '3'

    - name: Test Single File in a Directory
      if: always()
      uses: .
      with:
        name: Single Text File in Directory
        path: test_results/file_1.txt
        retention-days: '3'

    - name: Test Single File at Root Directory
      if: always()
      uses: .
      with:
        name: Single Test File at Root Directory
        path: file_0.txt
        retention-days: '3'
