name: Test Zip Upload Artifact

on:
  workflow_dispatch:

jobs:
  test-zip-upload-artifact:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Run Python Tests
      if: always()
      shell: bash
      run: |
        pip install pytest

        pytest -s ./src/test_zipper.py

    - name: Setup Files
      shell: bash
      run: |
        mkdir "temp"
        mkdir "temp/subfolder"

        echo "Test Root" > temp/test-root.txt
        echo "Test Sub 1" > temp/subfolder/test-sub1.txt
        echo "Test Sub 2" > temp/subfolder/test-sub2.txt

    - name: Artifact with Root and Sub 2
      if: always()
      uses: ./
      with:
        name: with-root-sub-2-no-sub1
        path: |
          temp/test-root.txt
          temp/subfolder/
          !temp/subfolder/test-sub2.txt

    - name: Artifact with Sub 1 and 2
      if: always()
      uses: ./
      with:
        name: with-sub1-and-sub2
        path: temp/subfolder

    - name: Artifact with Root
      if: always()
      uses: ./
      with:
        name: with-root
        path: temp/test-root.txt