name: Test Zip Upload Artifact

on:
  workflow_dispatch:

jobs:
  test-zip-upload-artifact:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Run Python Tests
      if: always()
      shell: bash
      run: |
        pip install pytest

        pytest ./src/test_zipper.py

    - name: Setup Files
      shell: bash
      run: |
        mkdir "temp"
        mkdir "temp/subfolder"
        touch "temp/test-root.txt"
        touch "temp/subfolder/test-sub1.txt"
        touch "temp/subfolder/test-sub2.txt"

    - name: Upload Artifact with Exclusions
      if: always()
      uses: actions/upload-artifact@v2
      with:
        name: test-artifact
        path: |
          temp/test-root.txt
          temp/subfolder/
          !temp/subfolder/test-sub2.txt
    