name: Test Zip Upload Artifact

on:
  workflow_dispatch:

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
    - name: Create Test Files
      shell: python
      run: |
        import os
        dir_results = "test_results"
        os.mkdir(dir_results)

        two_mb = 2 * 1024 * 1024

        path_file_1 = os.path.join(dir_results, "file_1.txt")
        print(f"Create file 1 at: {path_file_1}")
        with open(path_file_1, "w") as writer:
            writer.write("1" * two_mb)

        path_file_2 = os.path.join(dir_results, "file_2.txt")
        print(f"Create file 2 at: {path_file_1}")
        with open(path_file_2, "w") as writer:
            writer.write("2" * two_mb)

    - name: Directory With Files
      uses: im-open/zip-upload-artifact@v1
      with:
        name: Directory With Text Files
        path: test_results
        retention-days: '3'

    - name: Single File
      uses: im-open/zip-upload-artifact@v1
      with:
        name: Single Text File
        path: test_results/file_1.txt
        retention-days: '3'
